#Grphppers
import turtle as t
t.setup(1000,600)
t=t.Turtle()
t.speed(0)
t.color('coral')
for i in range(-500,500,5):
    t.setx(i)
    t.pendown()
    t.goto(i,500)
    t.penup()
    t.goto(i,-500)
    t.pendown()
    t.goto(i,0)
    t.penup()
t.pendown()
t.goto(0,0)
for i in range(-500,500,5):
    t.sety(i)
    t.pendown()
    t.goto(500,i)
    t.penup()
    t.goto(-500,i)
    t.pendown()
    t.goto(0,i)
    t.penup()
t.color('crimson')
for i in range(-500,500,50):
    t.setx(i)
    t.pendown()
    t.goto(i,500)
    t.penup()
    t.goto(i,-500)
    t.pendown()
    t.goto(i,0)
    t.penup()
t.pendown()
t.goto(0,0)
for i in range(-500,500,50):
    t.sety(i)
    t.pendown()
    t.goto(500,i)
    t.penup()
    t.goto(-500,i)
    t.pendown()
    t.goto(0,i)
    t.penup()

